vim.cmd("set expandtab")
vim.g.mapleader = " "
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set nowrap")
vim.cmd("set incsearch")
vim.cmd("set ignorecase")
